# config/validator/validation.yaml
Domain\Entity\Product:
  properties:
    name:
      - NotBlank: ~
      - Length:
          min: 2
          max: 20
          minMessage: 'The produt name must be at least {{ limit }} characters long'
          maxMessage: 'The product name cannot be longer than {{ limit }} characters'
    price:
      - Positive: ~